package com.baoliang.Model;


import java.util.HashSet;
import java.util.Set;

/**
 * Application generated by hbm2java
 */
public class Application implements java.io.Serializable {

	/**
	 * 
	 */
	private String acnum;
	private String boss;
	private String phone;
	private String goods;
	private String start;
	private String destination;
	private Set apses = new HashSet(0);

	public Application() {
	}

	public Application(String acnum) {
		this.acnum = acnum;
	}

	public Application(String acnum, String boss, String phone, String goods, String start, String destination,
			Set apses) {
		this.acnum = acnum;
		this.boss = boss;
		this.phone = phone;
		this.goods = goods;
		this.start = start;
		this.destination = destination;
		this.apses = apses;
	}

	public String getAcnum() {
		return this.acnum;
	}

	public void setAcnum(String acnum) {
		this.acnum = acnum;
	}

	public String getBoss() {
		return this.boss;
	}

	public void setBoss(String boss) {
		this.boss = boss;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getGoods() {
		return this.goods;
	}

	public void setGoods(String goods) {
		this.goods = goods;
	}

	public String getStart() {
		return this.start;
	}

	public void setStart(String start) {
		this.start = start;
	}

	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	public Set getApses() {
		return this.apses;
	}

	public void setApses(Set apses) {
		this.apses = apses;
	}

}
