// default package
// Generated 2018-1-5 11:37:21 by Hibernate Tools 5.2.6.Final
package com.baoliang.Model;
/**
 * Aps generated by hbm2java
 */
public class Aps implements java.io.Serializable {

	private int id;
	private Application application;
	private Drivers drivers;
	private String statue;

	public Aps() {
	}

	public Aps(int id) {
		this.id = id;
	}

	public Aps(int id, Application application, Drivers drivers, String statue) {
		this.id = id;
		this.application = application;
		this.drivers = drivers;
		this.statue = statue;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Application getApplication() {
		return this.application;
	}

	public void setApplication(Application application) {
		this.application = application;
	}

	public Drivers getDrivers() {
		return this.drivers;
	}

	public void setDrivers(Drivers drivers) {
		this.drivers = drivers;
	}

	public String getStatue() {
		return this.statue;
	}

	public void setStatue(String statue) {
		this.statue = statue;
	}

}
